# Generated by Django 2.2.3 on 2019-07-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swiper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_at', models.DateTimeField(auto_created=True)),
                ('uid', models.IntegerField()),
                ('sid', models.IntegerField()),
                ('mark', models.CharField(choices=[('like', '喜欢'), ('dislike', '不喜欢'), ('superlike', '超喜欢')], max_length=16)),
            ],
            options={
                'db_table': 'swiper',
            },
        ),
    ]
