# Generated by Django 2.2.4 on 2019-08-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0002_auto_20190802_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='vip',
            name='level',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='vip',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
